### ISSUE TITLE
Error during Adding a Tenant on ext V.1.3.10

### ISSUE THREAD

**Issue by RominPatel-Moodys** [yannick-beot-sp/vscode-sailpoint-identitynow#103]
hI

I am trying to configure the ISC Extension on my laptop using Visual basic. 

I am able to install the extension successfully but once i give the tenant name, display name and PAT, i get an error:

TypeError: Cannot read properties of undefined (reading 'status').

Can you please assist?

**Comment by RominPatel-Moodys** [comment]
When i tried to install V1.3.2 i get the following error:

Error: unable to get local issuer certificate

**Comment by yannick-beot-sp** [comment]
I manage to reproduce the problem if I don't set correctly the FQDN of the tenant.
When inviting to enter the tenant name (first input):
- If your tenant is using the domain "identitynow.com", you can enter either `<yourtenant>` or `<yourtenant>.identitynow.com`
- If you are using a vanity URL, you can still use the format above:  `<yourtenant>` or `<yourtenant>.identitynow.com`
- if you are using another domain (e.g. identitynow-demo.com), you have to put the FQDN, i.e. `<yourtenant>.identitynow-demo.com`

In no case, you must use the API FQDN.

I'll check why the error in not better catched

**Comment by RominPatel-Moodys** [comment]
still does not work for me

I am putting <mytenant>.identitynow.com

**Comment by yannick-beot-sp** [comment]
Can you reach out in the developer forum, through a direct message and share with me the logs:
1. Go to *Help* > *Toggle Developer Tools*.
2. Clear the console.
3. Reproduce the error.
4. Copy/paste the logs.

**Comment by RominPatel-Moodys** [comment]
Please find the logs.

console.ts:137 [Extension Host] > createSession 61f7410377de4534ad72d843729f7df7
console.ts:137 [Extension Host] > createAccessToken bcbsa.identitynow.com 47b69b3433004af1b7017b3c55f5832b
console.ts:137 [Extension Host] REQUEST: POST https://bcbsa.api.identitynow.com/oauth/token {}
log.ts:445   ERR [Extension Host] Unable to fetch access token. Aborting.
console.ts:137 [Extension Host] Unable to fetch access token. Aborting.
EYi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
log.ts:445   ERR [Extension Host] Error: TypeError: Cannot read properties of undefined (reading 'status')
	at io.getAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:596:1188)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async lr.createAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:596:3951)
	at async lr.createSession (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:596:3722)
	at async gp.execute (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:599:29686)
	at async cw.h (file:///c:/Users/PR493854/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
console.ts:137 [Extension Host] Error: TypeError: Cannot read properties of undefined (reading 'status')
	at io.getAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:596:1188)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async lr.createAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:596:3951)
	at async lr.createSession (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:596:3722)
	at async gp.execute (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.10\out\extension.js:599:29686)
	at async cw.h (file:///c:/Users/PR493854/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
EYi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
console.ts:137 [Extension Host] > removeTenantCredentials for 61f7410377de4534ad72d843729f7df7
notificationsAlerts.ts:42 TypeError: Cannot read properties of undefined (reading 'status')
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
B @ event.ts:1243
C @ event.ts:1254
fire @ event.ts:1278
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
fire @ ipc.net.ts:652
l.onmessage @ localProcessExtensionHost.ts:378
log.ts:435  WARN Settings pattern "issueReporter.*" doesn't match any settings
log.ts:435  WARN Settings pattern "application.*" doesn't match any settings
console.ts:137 [Extension Host] > onFileSaved {uri: {…}, fileName: 'c:\\Users\\PR493854\\OneDrive - Blue Cross Blue Shiel…ssociation\\Desktop\\Work\\Visio Setup\\Error Logs.md', isUntitled: false, languageId: 'markdown', version: 2, …}
log.ts:435  WARN Settings pattern "issueReporter.*" doesn't match any settings
log.ts:435  WARN Settings pattern "application.*" doesn't match any settings

**Comment by yannick-beot-sp** [comment]
Thank you @RominPatel-Moodys 
FQDN is just fine.
The only thing I'm thinking of is "bad credentials", meaning a wrong client id or client secret.
In any case, I have just released on updated version (1.3.11) that fix an issue in the error handler and that might provide a better error message.
Once you have updated the extension, can you try again and share again the logs?

**Comment by RominPatel-Moodys** [comment]
[Extension Host] > createSession 1b7a20ab5533425aaced81899a5abf0a
console.ts:137 [Extension Host] > createAccessToken bcbsa-sb2.identitynow.com 5876c443904a47b0bf0c6ca1f9bba322
console.ts:137 [Extension Host] REQUEST: POST https://bcbsa-sb2.api.identitynow.com/oauth/token {}
log.ts:445   ERR [Extension Host] [ISCClient] POST https://bcbsa-sb2.api.identitynow.com/oauth/token | Error undefined undefined Error: unable to get local issuer certificate
	at $i.from (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:589:13406)
	at xr.<anonymous> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:592:9956)
	at xr.emit (node:events:518:28)
	at UA.<computed> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:6:893)
	at ClientRequest.emit (node:events:530:35)
	at emitErrorEvent (node:_http_client:101:11)
	at TLSSocket.socketErrorListener (node:_http_client:504:5)
	at TLSSocket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
console.ts:137 [Extension Host] [ISCClient] POST https://bcbsa-sb2.api.identitynow.com/oauth/token | Error undefined undefined Error: unable to get local issuer certificate
	at $i.from (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:589:13406)
	at xr.<anonymous> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:592:9956)
	at xr.emit (node:events:518:28)
	at UA.<computed> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:6:893)
	at ClientRequest.emit (node:events:530:35)
	at emitErrorEvent (node:_http_client:101:11)
	at TLSSocket.socketErrorListener (node:_http_client:504:5)
	at TLSSocket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
log.ts:445   ERR [Extension Host] Unable to fetch access token. Aborting.
console.ts:137 [Extension Host] Unable to fetch access token. Aborting.
log.ts:445   ERR [Extension Host] Error: TypeError: Cannot read properties of undefined (reading 'headers')
	at io.getAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:1246)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async lr.createAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:4009)
	at async lr.createSession (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:3780)
	at async bp.execute (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:599:29710)
	at async cw.h (file:///c:/Users/PR493854/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
console.ts:137 [Extension Host] Error: TypeError: Cannot read properties of undefined (reading 'headers')
	at io.getAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:1246)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async lr.createAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:4009)
	at async lr.createSession (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:3780)
	at async bp.execute (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:599:29710)
	at async cw.h (file:///c:/Users/PR493854/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
console.ts:137 [Extension Host] > removeTenantCredentials for 1b7a20ab5533425aaced81899a5abf0a
notificationsAlerts.ts:42 TypeError: Cannot read properties of undefined (reading 'headers')
console.ts:137 [Extension Host] > createSession fcb4e93c3b1e4d96bddad4bb0d437130
console.ts:137 [Extension Host] > createAccessToken bcbsa-sb2.identitynow.com 5876c443904a47b0bf0c6ca1f9bba322
console.ts:137 [Extension Host] REQUEST: POST https://bcbsa-sb2.api.identitynow.com/oauth/token {}
log.ts:445   ERR [Extension Host] [ISCClient] POST https://bcbsa-sb2.api.identitynow.com/oauth/token | Error undefined undefined Error: unable to get local issuer certificate
	at $i.from (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:589:13406)
	at xr.<anonymous> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:592:9956)
	at xr.emit (node:events:518:28)
	at UA.<computed> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:6:893)
	at ClientRequest.emit (node:events:530:35)
	at emitErrorEvent (node:_http_client:101:11)
	at TLSSocket.socketErrorListener (node:_http_client:504:5)
	at TLSSocket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
console.ts:137 [Extension Host] [ISCClient] POST https://bcbsa-sb2.api.identitynow.com/oauth/token | Error undefined undefined Error: unable to get local issuer certificate
	at $i.from (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:589:13406)
	at xr.<anonymous> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:592:9956)
	at xr.emit (node:events:518:28)
	at UA.<computed> (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:6:893)
	at ClientRequest.emit (node:events:530:35)
	at emitErrorEvent (node:_http_client:101:11)
	at TLSSocket.socketErrorListener (node:_http_client:504:5)
	at TLSSocket.emit (node:events:518:28)
	at emitErrorNT (node:internal/streams/destroy:169:8)
	at emitErrorCloseNT (node:internal/streams/destroy:128:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
log.ts:445   ERR [Extension Host] Unable to fetch access token. Aborting.
console.ts:137 [Extension Host] Unable to fetch access token. Aborting.
log.ts:445   ERR [Extension Host] Error: TypeError: Cannot read properties of undefined (reading 'headers')
	at io.getAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:1246)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async lr.createAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:4009)
	at async lr.createSession (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:3780)
	at async bp.execute (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:599:29710)
	at async cw.h (file:///c:/Users/PR493854/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
console.ts:137 [Extension Host] Error: TypeError: Cannot read properties of undefined (reading 'headers')
	at io.getAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:1246)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async lr.createAccessToken (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:4009)
	at async lr.createSession (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:596:3780)
	at async bp.execute (c:\Users\PR493854\.vscode\extensions\yannick-beot-sp.vscode-sailpoint-identitynow-1.3.11\out\extension.js:599:29710)
	at async cw.h (file:///c:/Users/PR493854/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:32825)
console.ts:137 [Extension Host] > removeTenantCredentials for fcb4e93c3b1e4d96bddad4bb0d437130
notificationsAlerts.ts:42 TypeError: Cannot read properties of undefined (reading 'headers')

**Comment by yannick-beot-sp** [comment]
Interesting. So we are back to the certificate error you mentionned with the version 1.3.2.
You are not using the same tenant between your 2 tests. I guess that's because none of them are working.
There is a high chance that your organization is using a proxy with SSL introspection.
With your browser (Edge or Chrome), can you connect to https://bcbsa-sb2.api.identitynow.com/ without any certificate error or warning?

**Comment by yannick-beot-sp** [comment]
That's indeed the expected result.
My question was: do you have any certificate error when accessing this URL?
If you don't have any certificate error, it means that your browser is trusting the issuing CA.
Can you install https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca and try again?

**Comment by RominPatel-Moodys** [comment]
i installed the extension and am still getting an error

TypeError: Cannot read properties of undefined (reading 'headers')

**Comment by yannick-beot-sp** [comment]
It seems that the extension have some configuration:
Since v3.0.0 this extension has got some parameters, available at File / Preferences / Settings / Extensions / win-ca:

- Save (switch)

   - Enables/disables saving fetched certificates to disk

- Method of injection
  - None
    - do not inject: turns off the extension
  - Replace (Default)
    - built-in certificates with what Windows thinks are the root certificates (https.globalAgent.options.ca method)
  - Append
    - new experimental method, where both lists are used together (tls.createSecureContext() method)

Can you make sure that the setting `Method of injection` is not None.
If not, can you try `Append`? When you change this setting, you will need to restart VSCode.

Alternatively, if you are using a proxy with a self-signed certificate, you can set the http.proxyStrictSSL and https.proxyStrictSSL settings to false in your VSCode settings.json file:

```
{
  "http.proxyStrictSSL": false,
  "https.proxyStrictSSL": false
}
```

**Comment by yannick-beot-sp** [comment]
Closed as not responsive
